apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 2                    # 2 pods chalenge
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0           # ek samay mein sirf 0 pod unavailable hoga
      maxSurge: 1                 # ek samay mein sirf 1 extra pod create hoga
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: soumik61/rag-chat-api:latest    # tumhara Docker Hub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: GOOGLE_API_KEY
            - name: CHROMA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: CHROMA_API_KEY
            - name: CHROMA_TENANT
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: CHROMA_TENANT
            - name: CHROMA_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: CHROMA_DATABASE
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: REDIS_PASSWORD